ForJunior/ForJunior/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ForJunior.Models;

namespace ForJunior.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Тестовое задание: каталог фильмов, реализована возиожность просмотра списка фильмов в каталоге, " +
            "добавления фильмов в католог (для вошедших на сайт пользователей).";

            return View();
        }
        public ActionResult RegistrationNewFilm()
        {
            ViewBag.Message = "Страница регистрации нового фильма.";

            return View();
        }
        public ActionResult Succes()
        {
            ViewBag.Message = "Фильм успешно дабавлен в каталог!";

            return View();
        }
        public ActionResult Error()
        {
            ViewBag.Message = "Фильм в каталог не добавлен!";

            return View();
        }
        public ActionResult LookFilm(int id)
        {
            //ViewBag.Message = "";
            Context contex = new Context();
            var listFilmDB = contex.Film;

            var listFilm = listFilmDB.Where(film => film.Id == id);
            listFilm.GetEnumerator().MoveNext();
            Film film1 = listFilm.GetEnumerator().Current;
            Film currentFilm = new Film();


            foreach (Film film in listFilm)
            {
                currentFilm = film;
            }

            return View(currentFilm);
        }
        public ActionResult LooklistFilms()
        {
            Context contex = new Context();
            var listFilmDB = contex.Film;
            ListFilms listFilm = new ListFilms();

            foreach (Film a in listFilmDB)
            {
                listFilm.listFilms.Add(new RegistrationNewFilm { FilmName = a.Name, Description = a.Descriotion, Poster = a.Poster, Producer = a.Produser, Year = a.Year, ID = a.Id});
            }

            return View(listFilm);
        }
    }
}

ForJunior/ForJunior/Controllers/NewFilmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using ForJunior.Models;

namespace ForJunior.Controllers
{
    public class Context : DbContext
    {
        public Context()
            : base("film")
        {
            Database.SetInitializer(new DropCreateDatabaseIfModelChanges<Context>());
        }
        public DbSet<Film> Film { get; set; }
    }

    public class NewFilmController : Controller
    {
        public RedirectResult ActionForm(RegistrationNewFilm newFilm)
        {
            Film film = new Film {Name = newFilm.FilmName, Autor = HttpContext.User.Identity.Name, Year = newFilm.Year, Poster = newFilm.Poster, Descriotion = newFilm.Description,
             Produser = newFilm.Producer };
            Context contex = new Context();
            contex.Film.Add(film);
            if (contex.SaveChanges() > 0)
            {
                return Redirect("../Home/Succes");
            }
            return Redirect("../Home/Error");
        }

    }
}

ForJunior/ForJunior/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Домашняя страница";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
        </div>
    </section>
}

ForJunior/ForJunior/Views/Home/LookFilm.cshtml
@model ForJunior.Models.Film
@{
    ViewBag.Title = "Просмотр фильма";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table>
    <tbody>
        <tr>
            <td>Название фильма</td>
            <td>@Model.Name</td>
        </tr>
        <tr>
            <td>Постер</td>
            <td>@Model.Poster</td>
        </tr>
        <tr>
            <td>Режисер</td>
            <td>@Model.Produser</td>
        </tr>
        <tr>
            <td>Год выпуска</td>
            <td>@Model.Year</td>
        </tr>
        <tr>
            <td>Описание</td>
            <td>@Model.Descriotion</td>
        </tr>
        <tr>
            <td>Выложил</td>
            <td>@Model.Autor</td>
        </tr>
        <tr>
            <td>
                <input type="button" value="Редактровать" onclick=""/>
            </td>
        </tr>
    </tbody>
</table>

ForJunior/ForJunior/Views/Home/LooklistFilms.cshtml
@model ForJunior.Models.ListFilms
@{
    ViewBag.Title = "Просмотр списка фильмов:";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>LookForFilms</h2>
<table>
    <tbody>
        <tr>
            <th>Название фильна</th>
            <th>Постер фильма</th>
            <th>Режисер</th>
            <th>Год издания</th>
        </tr>
        @for(int i = 0; i < Model.listFilms.Count; i++)
        {            
               <tr>                    
                    <td>
                        <a href="~/Home/LookFilm?id=@Model.listFilms[i].ID">
                        @Model.listFilms[i].FilmName
                        </a>
                    </td>
                    <td>
                        <a href="~/Home/LookFilm?id=@Model.listFilms[i].ID">
                        @Model.listFilms[i].Poster
                            </a>
                    </td>
                    <td>
                        <a href="~/Home/LookFilm?id=@Model.listFilms[i].ID">
                        @Model.listFilms[i].Producer
                            </a>
                    </td>
                    <td>
                        <a href="~/Home/LookFilm?id=@Model.listFilms[i].ID">
                        @Model.listFilms[i].Year
                        </a>
                    </td>                    
                </tr>            
        }
    </tbody>
</table>

ForJunior/ForJunior/Views/Home/RegistrationNewFilm.cshtml
@model ForJunior.Models.RegistrationNewFilm
@{
    ViewBag.Title = "Регистрация нового фильма";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("ActionForm", "NewFilm", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <fieldset id="param">
        <legend>Форма регистрации</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.FilmName)
                @Html.TextBoxFor(m => m.FilmName)
            </li>
            <li>
                @Html.LabelFor(m => m.Poster)
                @Html.TextBoxFor(m => m.Poster)
            </li>
            <li>
                @Html.LabelFor(m => m.Year)
                @Html.TextBoxFor(m => m.Year)
            </li>
            <li>
                @Html.LabelFor(m => m.Description)
                @Html.TextAreaFor(m => m.Description)
            </li>
            <li>
                @Html.LabelFor(m => m.Producer)
                @Html.TextBoxFor(m => m.Producer)
            </li>
        </ol>
        <input type="submit" value="Регистрация" />
    </fieldset>
}

ForJunior/ForJunior/Views/Home/Succes.cshtml
@{
    ViewBag.Title = "Фильм добавлен!";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Фильм Добавлен!</h2>